version: "3.7"

services:
  gonggam-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwe123"
      MYSQL_DATABASE: "gonggam"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      TZ: Asia/Seoul
      LANG: "en_US.utf8"

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - ./database/datadir/:/var/lib/mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"

  gonggam-test-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "gonggam-test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      TZ: Asia/Seoul
      LANG: "en_US.utf8"

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - ./database-test/datadir/:/var/lib/mysql
    platform: linux/x86_64
    ports:
      - "3307:3306"
